apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    role: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: maquema/backend:hoy
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          #resources:
          #  requests:
          #    memory: "64Mi"
          #    cpu: "250m"
          #  limits:
          #    memory: "128Mi"
          #    cpu: "300m"               
          env:
            - name: SERVICE_CLOCK_PORT
              value: "5001"
          #  readinessProbe: 
          #   httpGet:
          #     path: /clock
          #     port: 5001
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe: 
          #   httpGet:
          #     path: /clock
          #     port: 5001
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-lb-ext
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      name: backend-lb-port
  selector:
    app: backend    







